version: '3'
services:
  app:
    container_name: docker-node-mongoo
    restart: always
    build: .
    ports:
      - '81:3000'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27018:27018'
